name: ReleaseWorkflow
on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name:  Stepup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: NPM Publish
        run: |
          yarn
          yarn build
          rm -rf app src
          yarn publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.npm_token }}'