name: ReleaseWorkflow
on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name:  Stepup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: NPM Publish
        run: |
          yarn
          yarn build
          rm -rf app src
          npm publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.npm_token }}'